version: "3"

services:
  app:
    build: .
    image: ${{ secrets.DOCKER_USERNAME }}/devops-example-app
    environment:
      - SERVER_MESSAGE="Hexlet Awesome Server"

  caddy:
    build:
      context: .
      dockerfile: services/caddy/Dockerfile
    image: ${{ secrets.DOCKER_USERNAME }}/devops-example-caddy
